import { chromium } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
if (process.env.RUN_BROWSER_TESTS !== '1') throw new Error('Start the app against the isolated integration-test database, then set RUN_BROWSER_TESTS=1. This check writes an inspection.');
await mkdir('.test-artifacts', { recursive: true });
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
try {
  await page.goto('http://localhost:3000/dashboard');
  await page.waitForURL('**/login');
  await page.getByLabel('Email').fill('test@example.com');
  await page.getByLabel('Password').fill('test-password-123');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.waitForURL('**/dashboard');
  await page.screenshot({ path: '.test-artifacts/dashboard.png', fullPage: true });
  await page.getByRole('link', { name: /Start weekly check/ }).click();
  await page.getByLabel('Name', { exact: true }).waitFor();
  assert.equal(await page.getByLabel('Name', { exact: true }).inputValue(), 'Alex');
  assert.equal(await page.locator('tbody tr').count(), 42);
  await page.getByLabel('Name', { exact: true }).fill('Browser inspector');
  const fields = page.locator('input[type=number]');
  for (let i = 0; i < await fields.count(); i++) await fields.nth(i).fill(i === 0 ? '110' : '100');
  await page.screenshot({ path: '.test-artifacts/water-desktop.png', fullPage: true });
  await page.getByRole('button', { name: 'Save inspection', exact: true }).click();
  await page.getByRole('heading', { name: 'Browser inspector' }).waitFor();
  await page.getByText('Inspection saved successfully.').waitFor();
  await page.screenshot({ path: '.test-artifacts/report.png', fullPage: true });
  await page.getByRole('button', { name: '← Back', exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: '.test-artifacts/water-mobile.png', fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
  await page.getByRole('link', { name: '← Dashboard' }).click();
  await page.getByRole('link', { name: /Temperature Logs/ }).click();
  await page.getByText('Hot and Cold Water Temperature Checks', { exact: true }).waitFor();
  await page.waitForFunction(() => !document.querySelector('#submitButton').disabled);
  assert.deepEqual(errors, []);
  console.log('Browser checks passed: login, dashboard, 42 outlets, save, report, mobile overflow and original temperature form.');
} finally { await browser.close(); }
